from binary_tree import BinaryTree

tree = BinaryTree()

tree.adicionar(5)
tree.adicionar(3)
tree.adicionar(7)
tree.adicionar(2)
tree.adicionar(4)
tree.adicionar(6)
tree.adicionar(9)
print("pre-ordem: ",end='')
print(tree.preOrder())
print("em-ordem:  ",end='')
print(tree.inOrder())
print("pos-ordem: ",end='')
print(tree.posOrder())
print("")
print("desenho fofo: ")
print("")
tree.printTree()